---
name: Cache Test
on: 
  - push
  - workflow_dispatch

jobs:
  cache:

    strategy:
      matrix:
        python-version: ["3.12"]
        platform: ["ubuntu-22.04"]
    runs-on: "${{ matrix.platform }}"

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Setup the specified Python version
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' 

      - run: |
          echo "Running on ${{ matrix.platform }}"
          python3 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Linting (pylama)
        run: pylama .

      - name: Linting (black)
        run: black --check .

