---
name: Linting
on: 
  - push
  - workflow_dispatch

jobs:
  linting:
    runs-on: "ubuntu-24.04"

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Setup the specified Python version
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          echo "Running on ${{ runner.os }}"
          python3 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Linting (pylama)
        run: pylama .

      - name: Linting (black)
        run: black --check .
