---
name: Testing GH Actions
on: 
  - push
jobs:
  poetry-deps:

    strategy:
      matrix:
        python-version: ["3.12"]
        platform: ["ubuntu-22.04"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.7.1
          poetry install --with dev

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Display installed packages
        run: pip list

