---
name: Secrets
on: 
  - push

jobs:
  testing_secrets:
    runs-on: "ubuntu-24.04"
    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      - run: python3 --version

      - run: echo "${{ secrets.MY_SECRET }}"

      - run: |
          ls -al ${{ secrets.HIDDEN_FILE }}

