---
name: "Linting and Tests"
on: 
  - push
  - pull_request
env:
  FORCE_COLOR: 1
  ENVIRONMENT: gh_actions

jobs:
  linting:
    runs-on: "ubuntu-24.04"

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Setup the specified Python version
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Linting (pylama)
        run: pylama .

      - name: Linting (black)
        run: black --check .

  pytest:
    needs: linting
    runs-on: "ubuntu-24.04"

    steps:
      # Checkout this repository
      - uses: actions/checkout@v4

      # Setup the specified Python version
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Execute Tests
        run: py.test -s -v tests/
